version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - curl -s https://getcomposer.org/installer | php
      - mv  composer.phar /usr/local/bin/composer
      - php --version
  pre_build:
    commands:
      - echo "php version"
      - php -v
  build:
    commands:
      - echo Build started on 'date'
      - mkdir -p build
      - ls -lah
      - echo Installing composer deps
      - composer install
      - tar -czf build/packages-dev.gz ./
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/packages-dev.gz
