version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - apt-get update
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - composer self-update
  pre_build:
    commands:
      - echo "php version"
      - php -v
      - composer install --no-interaction
  build:
    commands:
      - echo Build started on 'date'
      - php bin/console cache:clear --no-debug
      - php bin/console assets:install public
      - php bin/console cache:warmup
      - mkdir -p build
      - tar -czf build/packages-dev.gz --exclude=./.github --exclude=./build --exclude=./vendor ./

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/packages-dev.gz

  discard-paths: yes
